### ISSUE TITLE
Add CI workflows for PRs and pushes

### ISSUE THREAD

**Issue by joelanford** [operator-framework/oria-operator#30]
For both PRs and pushes:
- golangci-lint
- go-apidiff
- go fmt && git diff
- unit and e2e testing

For PRs:
- goreleaser build, but skip push/release

For `main` branch pushes:
- goreleaser build, push images with `main` tag

For tag pushes
- goreleaser build, push images with versions tags, publish github release.

**Comment by everettraven** [comment]
@joelanford I broke this out into multiple issues:
- #39 
- #40
- #41
- #42  
- #44
- #45

I *think* these issues covers everything, but before closing this issue in favor of all the separate issues I wanted to make sure it looked good to you as well

**Comment by everettraven** [comment]
closing this issue as per above comment
