### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by awgreene** [operator-framework/oria-operator#9]
**Goal:** Showcase that the oria-opeator can:
- Generate RBAC in a set of namespaces.
- Can control which users can interact with a CRD.

**Acceptance Criteria:**
- Spin up a cluster with the oria-operator running on it.
- Create a RukPak bundle that contains a CRD and a  ScopeTemplate CR.
- Grant the "operator" namespaced RBAC at the cluster level.
- Grant the "operator" namespaced RBAC in a set of namespaces.
- Create a ScopeTemplate for the CRD that grants a set of users the ability to interact with the CR.

**Comment by everettraven** [comment]
I believe this is finished as of #64. @laxmikantbpandhare can you confirm?

**Comment by laxmikantbpandhare** [comment]
Yes right and gave a demo during the `Sprint Demo meeting.

**Comment by everettraven** [comment]
Closing as per https://github.com/operator-framework/oria-operator/issues/9#issuecomment-1297214006
